/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {22, 1, 1};
static const casadi_int casadi_s4[3] = {6, 1, 1};
static const casadi_int casadi_s5[3] = {6, 6, 1};
static const casadi_int casadi_s6[3] = {6, 0, 1};

/* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt:(i0[4],i1[2],i2[0],i3[22])->(o0[6],o1[6x6],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  casadi_real a72;
  a00=arg[0]? arg[0][3] : 0;
  a01=5.0000000000000000e-01;
  a02=arg[1]? arg[1][1] : 0;
  a03=tan(a02);
  a04=(a01*a03);
  a05=atan(a04);
  a00=(a00+a05);
  a06=sin(a00);
  a07=arg[3]? arg[3][6] : 0;
  a08=arg[0]? arg[0][1] : 0;
  a09=arg[3]? arg[3][5] : 0;
  a09=(a08-a09);
  a10=casadi_sign(a09);
  a10=(a07*a10);
  a11=(a06*a10);
  a00=cos(a00);
  a12=1.;
  a13=(a12-a07);
  a14=(a00*a13);
  a11=(a11+a14);
  a14=arg[1]? arg[1][0] : 0;
  a15=(a11*a14);
  a16=arg[0]? arg[0][2] : 0;
  a17=(a16*a10);
  a18=(a00*a17);
  a19=(a16*a13);
  a20=(a06*a19);
  a18=(a18-a20);
  a20=sin(a05);
  a21=(a16*a20);
  a22=2.5000000000000000e+00;
  a21=(a21/a22);
  a23=(a18*a21);
  a15=(a15+a23);
  a23=2.3999999999999999e+00;
  a24=(a16*a00);
  a25=(a13*a24);
  a26=(a16*a06);
  a27=(a10*a26);
  a25=(a25+a27);
  a27=2.2000000000000002e+00;
  a28=arg[0]? arg[0][0] : 0;
  a29=arg[3]? arg[3][4] : 0;
  a29=(a28-a29);
  a30=3.;
  a29=(a29-a30);
  a29=(a29-a22);
  a29=(a13*a29);
  a09=casadi_fabs(a09);
  a31=2.0000000000000001e-01;
  a09=(a09-a31);
  a09=(a09-a12);
  a07=(a07*a09);
  a29=(a29+a07);
  a29=(a27*a29);
  a25=(a25+a29);
  a25=(a23*a25);
  a15=(a15+a25);
  a25=cos(a02);
  a29=casadi_sq(a25);
  a01=(a01/a29);
  a04=casadi_sq(a04);
  a04=(a12+a04);
  a07=(a01/a04);
  a09=(a00*a07);
  a32=(a16*a09);
  a33=(a10*a32);
  a34=(a06*a07);
  a35=(a16*a34);
  a36=(a13*a35);
  a33=(a33-a36);
  a36=(a33*a02);
  a15=(a15+a36);
  if (res[0]!=0) res[0][0]=a15;
  a15=arg[3]? arg[3][9] : 0;
  a36=arg[3]? arg[3][8] : 0;
  a36=(a08-a36);
  a37=casadi_sign(a36);
  a37=(a15*a37);
  a38=(a06*a37);
  a39=(a12-a15);
  a40=(a00*a39);
  a38=(a38+a40);
  a40=(a38*a14);
  a41=(a16*a37);
  a42=(a00*a41);
  a43=(a16*a39);
  a44=(a06*a43);
  a42=(a42-a44);
  a44=(a42*a21);
  a40=(a40+a44);
  a44=(a39*a24);
  a45=(a37*a26);
  a44=(a44+a45);
  a45=arg[3]? arg[3][7] : 0;
  a45=(a28-a45);
  a45=(a45-a30);
  a45=(a45-a22);
  a45=(a39*a45);
  a36=casadi_fabs(a36);
  a36=(a36-a31);
  a36=(a36-a12);
  a15=(a15*a36);
  a45=(a45+a15);
  a45=(a27*a45);
  a44=(a44+a45);
  a44=(a23*a44);
  a40=(a40+a44);
  a44=(a37*a32);
  a45=(a39*a35);
  a44=(a44-a45);
  a45=(a44*a02);
  a40=(a40+a45);
  if (res[0]!=0) res[0][1]=a40;
  a40=arg[3]? arg[3][12] : 0;
  a45=arg[3]? arg[3][11] : 0;
  a45=(a08-a45);
  a15=casadi_sign(a45);
  a15=(a40*a15);
  a36=(a06*a15);
  a46=(a12-a40);
  a47=(a00*a46);
  a36=(a36+a47);
  a47=(a36*a14);
  a48=(a16*a15);
  a49=(a00*a48);
  a50=(a16*a46);
  a51=(a06*a50);
  a49=(a49-a51);
  a51=(a49*a21);
  a47=(a47+a51);
  a51=(a46*a24);
  a52=(a15*a26);
  a51=(a51+a52);
  a52=arg[3]? arg[3][10] : 0;
  a52=(a28-a52);
  a52=(a52-a30);
  a52=(a52-a22);
  a52=(a46*a52);
  a45=casadi_fabs(a45);
  a45=(a45-a31);
  a45=(a45-a12);
  a40=(a40*a45);
  a52=(a52+a40);
  a52=(a27*a52);
  a51=(a51+a52);
  a51=(a23*a51);
  a47=(a47+a51);
  a51=(a15*a32);
  a52=(a46*a35);
  a51=(a51-a52);
  a52=(a51*a02);
  a47=(a47+a52);
  if (res[0]!=0) res[0][2]=a47;
  a47=arg[3]? arg[3][15] : 0;
  a52=arg[3]? arg[3][14] : 0;
  a52=(a08-a52);
  a40=casadi_sign(a52);
  a40=(a47*a40);
  a45=(a06*a40);
  a53=(a12-a47);
  a54=(a00*a53);
  a45=(a45+a54);
  a54=(a45*a14);
  a55=(a16*a40);
  a56=(a00*a55);
  a57=(a16*a53);
  a58=(a06*a57);
  a56=(a56-a58);
  a58=(a56*a21);
  a54=(a54+a58);
  a58=(a53*a24);
  a59=(a40*a26);
  a58=(a58+a59);
  a59=arg[3]? arg[3][13] : 0;
  a59=(a28-a59);
  a59=(a59-a30);
  a59=(a59-a22);
  a59=(a53*a59);
  a52=casadi_fabs(a52);
  a52=(a52-a31);
  a52=(a52-a12);
  a47=(a47*a52);
  a59=(a59+a47);
  a59=(a27*a59);
  a58=(a58+a59);
  a58=(a23*a58);
  a54=(a54+a58);
  a58=(a40*a32);
  a59=(a53*a35);
  a58=(a58-a59);
  a59=(a58*a02);
  a54=(a54+a59);
  if (res[0]!=0) res[0][3]=a54;
  a54=arg[3]? arg[3][18] : 0;
  a59=arg[3]? arg[3][17] : 0;
  a59=(a08-a59);
  a47=casadi_sign(a59);
  a47=(a54*a47);
  a52=(a06*a47);
  a60=(a12-a54);
  a61=(a00*a60);
  a52=(a52+a61);
  a61=(a52*a14);
  a62=(a16*a47);
  a63=(a00*a62);
  a64=(a16*a60);
  a65=(a06*a64);
  a63=(a63-a65);
  a65=(a63*a21);
  a61=(a61+a65);
  a65=(a60*a24);
  a66=(a47*a26);
  a65=(a65+a66);
  a66=arg[3]? arg[3][16] : 0;
  a66=(a28-a66);
  a66=(a66-a30);
  a66=(a66-a22);
  a66=(a60*a66);
  a59=casadi_fabs(a59);
  a59=(a59-a31);
  a59=(a59-a12);
  a54=(a54*a59);
  a66=(a66+a54);
  a66=(a27*a66);
  a65=(a65+a66);
  a65=(a23*a65);
  a61=(a61+a65);
  a65=(a47*a32);
  a66=(a60*a35);
  a65=(a65-a66);
  a66=(a65*a02);
  a61=(a61+a66);
  if (res[0]!=0) res[0][4]=a61;
  a61=arg[3]? arg[3][21] : 0;
  a66=arg[3]? arg[3][20] : 0;
  a08=(a08-a66);
  a66=casadi_sign(a08);
  a66=(a61*a66);
  a54=(a06*a66);
  a59=(a12-a61);
  a67=(a00*a59);
  a54=(a54+a67);
  a67=(a54*a14);
  a68=(a16*a66);
  a69=(a00*a68);
  a70=(a16*a59);
  a71=(a06*a70);
  a69=(a69-a71);
  a71=(a69*a21);
  a67=(a67+a71);
  a71=(a59*a24);
  a72=(a66*a26);
  a71=(a71+a72);
  a72=arg[3]? arg[3][19] : 0;
  a28=(a28-a72);
  a28=(a28-a30);
  a28=(a28-a22);
  a28=(a59*a28);
  a08=casadi_fabs(a08);
  a08=(a08-a31);
  a08=(a08-a12);
  a61=(a61*a08);
  a28=(a28+a61);
  a28=(a27*a28);
  a71=(a71+a28);
  a71=(a23*a71);
  a67=(a67+a71);
  a32=(a66*a32);
  a35=(a59*a35);
  a32=(a32-a35);
  a35=(a32*a02);
  a67=(a67+a35);
  if (res[0]!=0) res[0][5]=a67;
  if (res[1]!=0) res[1][0]=a11;
  a11=(a10*a09);
  a67=(a13*a34);
  a11=(a11-a67);
  a67=(a14*a11);
  a35=4.0000000000000002e-01;
  a05=cos(a05);
  a05=(a05*a07);
  a05=(a16*a05);
  a05=(a35*a05);
  a71=(a18*a05);
  a28=(a17*a34);
  a61=(a19*a09);
  a28=(a28+a61);
  a28=(a21*a28);
  a71=(a71-a28);
  a67=(a67+a71);
  a71=(a23*a33);
  a67=(a67+a71);
  a29=(a01/a29);
  a25=(a25+a25);
  a71=sin(a02);
  a25=(a25*a71);
  a29=(a29*a25);
  a29=(a29/a04);
  a04=(a07/a04);
  a03=(a03*a01);
  a04=(a04*a03);
  a29=(a29-a04);
  a04=(a00*a29);
  a03=(a07*a34);
  a04=(a04-a03);
  a04=(a16*a04);
  a03=(a10*a04);
  a01=(a07*a09);
  a29=(a06*a29);
  a01=(a01+a29);
  a01=(a16*a01);
  a29=(a13*a01);
  a03=(a03-a29);
  a03=(a02*a03);
  a03=(a03+a33);
  a67=(a67+a03);
  if (res[1]!=0) res[1][1]=a67;
  a67=(a27*a13);
  a67=(a23*a67);
  if (res[1]!=0) res[1][2]=a67;
  a67=(a27*a10);
  a67=(a23*a67);
  if (res[1]!=0) res[1][3]=a67;
  a67=(a00*a10);
  a03=(a06*a13);
  a67=(a67-a03);
  a67=(a21*a67);
  a35=(a35*a20);
  a18=(a18*a35);
  a67=(a67+a18);
  a18=(a13*a00);
  a20=(a10*a06);
  a18=(a18+a20);
  a18=(a23*a18);
  a67=(a67+a18);
  a11=(a02*a11);
  a67=(a67+a11);
  if (res[1]!=0) res[1][4]=a67;
  a67=(a10*a00);
  a11=(a13*a06);
  a67=(a67-a11);
  a67=(a14*a67);
  a17=(a17*a06);
  a19=(a19*a00);
  a17=(a17+a19);
  a17=(a21*a17);
  a67=(a67-a17);
  a17=(a10*a24);
  a19=(a13*a26);
  a17=(a17-a19);
  a17=(a23*a17);
  a67=(a67+a17);
  a17=(a07*a06);
  a17=(a16*a17);
  a10=(a10*a17);
  a07=(a07*a00);
  a16=(a16*a07);
  a13=(a13*a16);
  a10=(a10+a13);
  a10=(a02*a10);
  a67=(a67-a10);
  if (res[1]!=0) res[1][5]=a67;
  if (res[1]!=0) res[1][6]=a38;
  a38=(a37*a09);
  a67=(a39*a34);
  a38=(a38-a67);
  a67=(a14*a38);
  a10=(a42*a05);
  a13=(a41*a34);
  a07=(a43*a09);
  a13=(a13+a07);
  a13=(a21*a13);
  a10=(a10-a13);
  a67=(a67+a10);
  a10=(a23*a44);
  a67=(a67+a10);
  a10=(a37*a04);
  a13=(a39*a01);
  a10=(a10-a13);
  a10=(a02*a10);
  a10=(a10+a44);
  a67=(a67+a10);
  if (res[1]!=0) res[1][7]=a67;
  a67=(a27*a39);
  a67=(a23*a67);
  if (res[1]!=0) res[1][8]=a67;
  a67=(a27*a37);
  a67=(a23*a67);
  if (res[1]!=0) res[1][9]=a67;
  a67=(a00*a37);
  a10=(a06*a39);
  a67=(a67-a10);
  a67=(a21*a67);
  a42=(a42*a35);
  a67=(a67+a42);
  a42=(a39*a00);
  a10=(a37*a06);
  a42=(a42+a10);
  a42=(a23*a42);
  a67=(a67+a42);
  a38=(a02*a38);
  a67=(a67+a38);
  if (res[1]!=0) res[1][10]=a67;
  a67=(a37*a00);
  a38=(a39*a06);
  a67=(a67-a38);
  a67=(a14*a67);
  a41=(a41*a06);
  a43=(a43*a00);
  a41=(a41+a43);
  a41=(a21*a41);
  a67=(a67-a41);
  a41=(a37*a24);
  a43=(a39*a26);
  a41=(a41-a43);
  a41=(a23*a41);
  a67=(a67+a41);
  a37=(a37*a17);
  a39=(a39*a16);
  a37=(a37+a39);
  a37=(a02*a37);
  a67=(a67-a37);
  if (res[1]!=0) res[1][11]=a67;
  if (res[1]!=0) res[1][12]=a36;
  a36=(a15*a09);
  a67=(a46*a34);
  a36=(a36-a67);
  a67=(a14*a36);
  a37=(a49*a05);
  a39=(a48*a34);
  a41=(a50*a09);
  a39=(a39+a41);
  a39=(a21*a39);
  a37=(a37-a39);
  a67=(a67+a37);
  a37=(a23*a51);
  a67=(a67+a37);
  a37=(a15*a04);
  a39=(a46*a01);
  a37=(a37-a39);
  a37=(a02*a37);
  a37=(a37+a51);
  a67=(a67+a37);
  if (res[1]!=0) res[1][13]=a67;
  a67=(a27*a46);
  a67=(a23*a67);
  if (res[1]!=0) res[1][14]=a67;
  a67=(a27*a15);
  a67=(a23*a67);
  if (res[1]!=0) res[1][15]=a67;
  a67=(a00*a15);
  a37=(a06*a46);
  a67=(a67-a37);
  a67=(a21*a67);
  a49=(a49*a35);
  a67=(a67+a49);
  a49=(a46*a00);
  a37=(a15*a06);
  a49=(a49+a37);
  a49=(a23*a49);
  a67=(a67+a49);
  a36=(a02*a36);
  a67=(a67+a36);
  if (res[1]!=0) res[1][16]=a67;
  a67=(a15*a00);
  a36=(a46*a06);
  a67=(a67-a36);
  a67=(a14*a67);
  a48=(a48*a06);
  a50=(a50*a00);
  a48=(a48+a50);
  a48=(a21*a48);
  a67=(a67-a48);
  a48=(a15*a24);
  a50=(a46*a26);
  a48=(a48-a50);
  a48=(a23*a48);
  a67=(a67+a48);
  a15=(a15*a17);
  a46=(a46*a16);
  a15=(a15+a46);
  a15=(a02*a15);
  a67=(a67-a15);
  if (res[1]!=0) res[1][17]=a67;
  if (res[1]!=0) res[1][18]=a45;
  a45=(a40*a09);
  a67=(a53*a34);
  a45=(a45-a67);
  a67=(a14*a45);
  a15=(a56*a05);
  a46=(a55*a34);
  a48=(a57*a09);
  a46=(a46+a48);
  a46=(a21*a46);
  a15=(a15-a46);
  a67=(a67+a15);
  a15=(a23*a58);
  a67=(a67+a15);
  a15=(a40*a04);
  a46=(a53*a01);
  a15=(a15-a46);
  a15=(a02*a15);
  a15=(a15+a58);
  a67=(a67+a15);
  if (res[1]!=0) res[1][19]=a67;
  a67=(a27*a53);
  a67=(a23*a67);
  if (res[1]!=0) res[1][20]=a67;
  a67=(a27*a40);
  a67=(a23*a67);
  if (res[1]!=0) res[1][21]=a67;
  a67=(a00*a40);
  a15=(a06*a53);
  a67=(a67-a15);
  a67=(a21*a67);
  a56=(a56*a35);
  a67=(a67+a56);
  a56=(a53*a00);
  a15=(a40*a06);
  a56=(a56+a15);
  a56=(a23*a56);
  a67=(a67+a56);
  a45=(a02*a45);
  a67=(a67+a45);
  if (res[1]!=0) res[1][22]=a67;
  a67=(a40*a00);
  a45=(a53*a06);
  a67=(a67-a45);
  a67=(a14*a67);
  a55=(a55*a06);
  a57=(a57*a00);
  a55=(a55+a57);
  a55=(a21*a55);
  a67=(a67-a55);
  a55=(a40*a24);
  a57=(a53*a26);
  a55=(a55-a57);
  a55=(a23*a55);
  a67=(a67+a55);
  a40=(a40*a17);
  a53=(a53*a16);
  a40=(a40+a53);
  a40=(a02*a40);
  a67=(a67-a40);
  if (res[1]!=0) res[1][23]=a67;
  if (res[1]!=0) res[1][24]=a52;
  a52=(a47*a09);
  a67=(a60*a34);
  a52=(a52-a67);
  a67=(a14*a52);
  a40=(a63*a05);
  a53=(a62*a34);
  a55=(a64*a09);
  a53=(a53+a55);
  a53=(a21*a53);
  a40=(a40-a53);
  a67=(a67+a40);
  a40=(a23*a65);
  a67=(a67+a40);
  a40=(a47*a04);
  a53=(a60*a01);
  a40=(a40-a53);
  a40=(a02*a40);
  a40=(a40+a65);
  a67=(a67+a40);
  if (res[1]!=0) res[1][25]=a67;
  a67=(a27*a60);
  a67=(a23*a67);
  if (res[1]!=0) res[1][26]=a67;
  a67=(a27*a47);
  a67=(a23*a67);
  if (res[1]!=0) res[1][27]=a67;
  a67=(a00*a47);
  a40=(a06*a60);
  a67=(a67-a40);
  a67=(a21*a67);
  a63=(a63*a35);
  a67=(a67+a63);
  a63=(a60*a00);
  a40=(a47*a06);
  a63=(a63+a40);
  a63=(a23*a63);
  a67=(a67+a63);
  a52=(a02*a52);
  a67=(a67+a52);
  if (res[1]!=0) res[1][28]=a67;
  a67=(a47*a00);
  a52=(a60*a06);
  a67=(a67-a52);
  a67=(a14*a67);
  a62=(a62*a06);
  a64=(a64*a00);
  a62=(a62+a64);
  a62=(a21*a62);
  a67=(a67-a62);
  a62=(a47*a24);
  a64=(a60*a26);
  a62=(a62-a64);
  a62=(a23*a62);
  a67=(a67+a62);
  a47=(a47*a17);
  a60=(a60*a16);
  a47=(a47+a60);
  a47=(a02*a47);
  a67=(a67-a47);
  if (res[1]!=0) res[1][29]=a67;
  if (res[1]!=0) res[1][30]=a54;
  a54=(a66*a09);
  a67=(a59*a34);
  a54=(a54-a67);
  a67=(a14*a54);
  a05=(a69*a05);
  a34=(a68*a34);
  a09=(a70*a09);
  a34=(a34+a09);
  a34=(a21*a34);
  a05=(a05-a34);
  a67=(a67+a05);
  a05=(a23*a32);
  a67=(a67+a05);
  a04=(a66*a04);
  a01=(a59*a01);
  a04=(a04-a01);
  a04=(a02*a04);
  a04=(a04+a32);
  a67=(a67+a04);
  if (res[1]!=0) res[1][31]=a67;
  a67=(a27*a59);
  a67=(a23*a67);
  if (res[1]!=0) res[1][32]=a67;
  a27=(a27*a66);
  a27=(a23*a27);
  if (res[1]!=0) res[1][33]=a27;
  a27=(a00*a66);
  a67=(a06*a59);
  a27=(a27-a67);
  a27=(a21*a27);
  a69=(a69*a35);
  a27=(a27+a69);
  a69=(a59*a00);
  a35=(a66*a06);
  a69=(a69+a35);
  a69=(a23*a69);
  a27=(a27+a69);
  a54=(a02*a54);
  a27=(a27+a54);
  if (res[1]!=0) res[1][34]=a27;
  a27=(a66*a00);
  a54=(a59*a06);
  a27=(a27-a54);
  a14=(a14*a27);
  a68=(a68*a06);
  a70=(a70*a00);
  a68=(a68+a70);
  a21=(a21*a68);
  a14=(a14-a21);
  a24=(a66*a24);
  a26=(a59*a26);
  a24=(a24-a26);
  a23=(a23*a24);
  a14=(a14+a23);
  a66=(a66*a17);
  a59=(a59*a16);
  a66=(a66+a59);
  a02=(a02*a66);
  a14=(a14-a02);
  if (res[1]!=0) res[1][35]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
