/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {22, 1, 1};
static const casadi_int casadi_s4[3] = {6, 1, 1};
static const casadi_int casadi_s5[3] = {6, 6, 1};
static const casadi_int casadi_s6[3] = {6, 0, 1};

/* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt:(i0[4],i1[2],i2[0],i3[22])->(o0[6],o1[6x6],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61;
  a00=arg[0]? arg[0][3] : 0;
  a01=5.0000000000000000e-01;
  a02=arg[1]? arg[1][1] : 0;
  a03=tan(a02);
  a04=(a01*a03);
  a05=atan(a04);
  a00=(a00+a05);
  a06=sin(a00);
  a07=2.0000000000000001e-01;
  a08=arg[0]? arg[0][1] : 0;
  a09=arg[3]? arg[3][5] : 0;
  a09=(a08-a09);
  a10=casadi_sign(a09);
  a10=(a07*a10);
  a11=(a06*a10);
  a12=3.;
  a00=cos(a00);
  a13=(a12*a00);
  a11=(a11+a13);
  a14=arg[1]? arg[1][0] : 0;
  a15=(a11*a14);
  a16=arg[0]? arg[0][2] : 0;
  a17=(a16*a10);
  a18=(a00*a17);
  a19=(a12*a16);
  a20=(a06*a19);
  a18=(a18-a20);
  a21=sin(a05);
  a22=(a16*a21);
  a23=2.5000000000000000e+00;
  a22=(a22/a23);
  a24=(a18*a22);
  a15=(a15+a24);
  a24=2.3999999999999999e+00;
  a25=(a16*a00);
  a26=(a12*a25);
  a27=(a16*a06);
  a28=(a10*a27);
  a28=(a26+a28);
  a29=2.2000000000000002e+00;
  a30=arg[0]? arg[0][0] : 0;
  a31=arg[3]? arg[3][4] : 0;
  a31=(a30-a31);
  a31=(a31-a12);
  a31=(a31-a23);
  a31=(a12*a31);
  a09=casadi_fabs(a09);
  a09=(a09-a07);
  a32=1.;
  a09=(a09-a32);
  a09=(a07*a09);
  a31=(a31+a09);
  a31=(a29*a31);
  a28=(a28+a31);
  a28=(a24*a28);
  a15=(a15+a28);
  a28=cos(a02);
  a31=casadi_sq(a28);
  a01=(a01/a31);
  a04=casadi_sq(a04);
  a04=(a32+a04);
  a09=(a01/a04);
  a33=(a00*a09);
  a34=(a16*a33);
  a35=(a10*a34);
  a36=(a06*a09);
  a37=(a16*a36);
  a37=(a12*a37);
  a35=(a35-a37);
  a38=(a35*a02);
  a15=(a15+a38);
  a15=(-a15);
  if (res[0]!=0) res[0][0]=a15;
  a15=arg[3]? arg[3][8] : 0;
  a15=(a08-a15);
  a38=casadi_sign(a15);
  a38=(a07*a38);
  a39=(a06*a38);
  a39=(a39+a13);
  a40=(a39*a14);
  a41=(a16*a38);
  a42=(a00*a41);
  a42=(a42-a20);
  a43=(a42*a22);
  a40=(a40+a43);
  a43=(a38*a27);
  a43=(a26+a43);
  a44=arg[3]? arg[3][7] : 0;
  a44=(a30-a44);
  a44=(a44-a12);
  a44=(a44-a23);
  a44=(a12*a44);
  a15=casadi_fabs(a15);
  a15=(a15-a07);
  a15=(a15-a32);
  a15=(a07*a15);
  a44=(a44+a15);
  a44=(a29*a44);
  a43=(a43+a44);
  a43=(a24*a43);
  a40=(a40+a43);
  a43=(a38*a34);
  a43=(a43-a37);
  a44=(a43*a02);
  a40=(a40+a44);
  a40=(-a40);
  if (res[0]!=0) res[0][1]=a40;
  a40=arg[3]? arg[3][11] : 0;
  a40=(a08-a40);
  a44=casadi_sign(a40);
  a44=(a07*a44);
  a15=(a06*a44);
  a15=(a15+a13);
  a45=(a15*a14);
  a46=(a16*a44);
  a47=(a00*a46);
  a47=(a47-a20);
  a48=(a47*a22);
  a45=(a45+a48);
  a48=(a44*a27);
  a48=(a26+a48);
  a49=arg[3]? arg[3][10] : 0;
  a49=(a30-a49);
  a49=(a49-a12);
  a49=(a49-a23);
  a49=(a12*a49);
  a40=casadi_fabs(a40);
  a40=(a40-a07);
  a40=(a40-a32);
  a40=(a07*a40);
  a49=(a49+a40);
  a49=(a29*a49);
  a48=(a48+a49);
  a48=(a24*a48);
  a45=(a45+a48);
  a48=(a44*a34);
  a48=(a48-a37);
  a49=(a48*a02);
  a45=(a45+a49);
  a45=(-a45);
  if (res[0]!=0) res[0][2]=a45;
  a45=arg[3]? arg[3][14] : 0;
  a45=(a08-a45);
  a49=casadi_sign(a45);
  a49=(a07*a49);
  a40=(a06*a49);
  a40=(a40+a13);
  a50=(a40*a14);
  a51=(a16*a49);
  a52=(a00*a51);
  a52=(a52-a20);
  a53=(a52*a22);
  a50=(a50+a53);
  a53=(a49*a27);
  a53=(a26+a53);
  a54=arg[3]? arg[3][13] : 0;
  a54=(a30-a54);
  a54=(a54-a12);
  a54=(a54-a23);
  a54=(a12*a54);
  a45=casadi_fabs(a45);
  a45=(a45-a07);
  a45=(a45-a32);
  a45=(a07*a45);
  a54=(a54+a45);
  a54=(a29*a54);
  a53=(a53+a54);
  a53=(a24*a53);
  a50=(a50+a53);
  a53=(a49*a34);
  a53=(a53-a37);
  a54=(a53*a02);
  a50=(a50+a54);
  a50=(-a50);
  if (res[0]!=0) res[0][3]=a50;
  a50=arg[3]? arg[3][17] : 0;
  a50=(a08-a50);
  a54=casadi_sign(a50);
  a54=(a07*a54);
  a45=(a06*a54);
  a45=(a45+a13);
  a55=(a45*a14);
  a56=(a16*a54);
  a57=(a00*a56);
  a57=(a57-a20);
  a58=(a57*a22);
  a55=(a55+a58);
  a58=(a54*a27);
  a58=(a26+a58);
  a59=arg[3]? arg[3][16] : 0;
  a59=(a30-a59);
  a59=(a59-a12);
  a59=(a59-a23);
  a59=(a12*a59);
  a50=casadi_fabs(a50);
  a50=(a50-a07);
  a50=(a50-a32);
  a50=(a07*a50);
  a59=(a59+a50);
  a59=(a29*a59);
  a58=(a58+a59);
  a58=(a24*a58);
  a55=(a55+a58);
  a58=(a54*a34);
  a58=(a58-a37);
  a59=(a58*a02);
  a55=(a55+a59);
  a55=(-a55);
  if (res[0]!=0) res[0][4]=a55;
  a55=arg[3]? arg[3][20] : 0;
  a08=(a08-a55);
  a55=casadi_sign(a08);
  a55=(a07*a55);
  a59=(a06*a55);
  a59=(a59+a13);
  a50=(a59*a14);
  a60=(a16*a55);
  a61=(a00*a60);
  a61=(a61-a20);
  a20=(a61*a22);
  a50=(a50+a20);
  a20=(a55*a27);
  a26=(a26+a20);
  a20=arg[3]? arg[3][19] : 0;
  a30=(a30-a20);
  a30=(a30-a12);
  a30=(a30-a23);
  a30=(a12*a30);
  a08=casadi_fabs(a08);
  a08=(a08-a07);
  a08=(a08-a32);
  a07=(a07*a08);
  a30=(a30+a07);
  a30=(a29*a30);
  a26=(a26+a30);
  a26=(a24*a26);
  a50=(a50+a26);
  a34=(a55*a34);
  a34=(a34-a37);
  a37=(a34*a02);
  a50=(a50+a37);
  a50=(-a50);
  if (res[0]!=0) res[0][5]=a50;
  a11=(-a11);
  if (res[1]!=0) res[1][0]=a11;
  a11=(a10*a33);
  a50=(a12*a36);
  a11=(a11-a50);
  a37=(a14*a11);
  a26=4.0000000000000002e-01;
  a05=cos(a05);
  a05=(a05*a09);
  a05=(a16*a05);
  a05=(a26*a05);
  a30=(a18*a05);
  a07=(a17*a36);
  a08=(a19*a33);
  a07=(a07+a08);
  a07=(a22*a07);
  a30=(a30-a07);
  a37=(a37+a30);
  a30=(a24*a35);
  a37=(a37+a30);
  a31=(a01/a31);
  a28=(a28+a28);
  a30=sin(a02);
  a28=(a28*a30);
  a31=(a31*a28);
  a31=(a31/a04);
  a04=(a09/a04);
  a03=(a03*a01);
  a04=(a04*a03);
  a31=(a31-a04);
  a04=(a00*a31);
  a03=(a09*a36);
  a04=(a04-a03);
  a04=(a16*a04);
  a03=(a10*a04);
  a01=(a09*a33);
  a31=(a06*a31);
  a01=(a01+a31);
  a01=(a16*a01);
  a01=(a12*a01);
  a03=(a03-a01);
  a03=(a02*a03);
  a03=(a03+a35);
  a37=(a37+a03);
  a37=(-a37);
  if (res[1]!=0) res[1][1]=a37;
  a37=-1.5840000000000000e+01;
  if (res[1]!=0) res[1][2]=a37;
  a03=(a29*a10);
  a03=(a24*a03);
  a03=(-a03);
  if (res[1]!=0) res[1][3]=a03;
  a03=(a00*a10);
  a35=(a12*a06);
  a03=(a03-a35);
  a03=(a22*a03);
  a26=(a26*a21);
  a18=(a18*a26);
  a03=(a03+a18);
  a18=(a10*a06);
  a18=(a13+a18);
  a18=(a24*a18);
  a03=(a03+a18);
  a11=(a02*a11);
  a03=(a03+a11);
  a03=(-a03);
  if (res[1]!=0) res[1][4]=a03;
  a03=(a10*a00);
  a03=(a03-a35);
  a03=(a14*a03);
  a17=(a17*a06);
  a19=(a19*a00);
  a17=(a17+a19);
  a17=(a22*a17);
  a03=(a03-a17);
  a17=(a10*a25);
  a27=(a12*a27);
  a17=(a17-a27);
  a17=(a24*a17);
  a03=(a03+a17);
  a17=(a09*a06);
  a17=(a16*a17);
  a10=(a10*a17);
  a09=(a09*a00);
  a16=(a16*a09);
  a12=(a12*a16);
  a10=(a10+a12);
  a10=(a02*a10);
  a03=(a03-a10);
  a03=(-a03);
  if (res[1]!=0) res[1][5]=a03;
  a39=(-a39);
  if (res[1]!=0) res[1][6]=a39;
  a39=(a38*a33);
  a39=(a39-a50);
  a03=(a14*a39);
  a10=(a42*a05);
  a16=(a41*a36);
  a16=(a16+a08);
  a16=(a22*a16);
  a10=(a10-a16);
  a03=(a03+a10);
  a10=(a24*a43);
  a03=(a03+a10);
  a10=(a38*a04);
  a10=(a10-a01);
  a10=(a02*a10);
  a10=(a10+a43);
  a03=(a03+a10);
  a03=(-a03);
  if (res[1]!=0) res[1][7]=a03;
  if (res[1]!=0) res[1][8]=a37;
  a03=(a29*a38);
  a03=(a24*a03);
  a03=(-a03);
  if (res[1]!=0) res[1][9]=a03;
  a03=(a00*a38);
  a03=(a03-a35);
  a03=(a22*a03);
  a42=(a42*a26);
  a03=(a03+a42);
  a42=(a38*a06);
  a42=(a13+a42);
  a42=(a24*a42);
  a03=(a03+a42);
  a39=(a02*a39);
  a03=(a03+a39);
  a03=(-a03);
  if (res[1]!=0) res[1][10]=a03;
  a03=(a38*a00);
  a03=(a03-a35);
  a03=(a14*a03);
  a41=(a41*a06);
  a41=(a41+a19);
  a41=(a22*a41);
  a03=(a03-a41);
  a41=(a38*a25);
  a41=(a41-a27);
  a41=(a24*a41);
  a03=(a03+a41);
  a38=(a38*a17);
  a38=(a38+a12);
  a38=(a02*a38);
  a03=(a03-a38);
  a03=(-a03);
  if (res[1]!=0) res[1][11]=a03;
  a15=(-a15);
  if (res[1]!=0) res[1][12]=a15;
  a15=(a44*a33);
  a15=(a15-a50);
  a03=(a14*a15);
  a38=(a47*a05);
  a41=(a46*a36);
  a41=(a41+a08);
  a41=(a22*a41);
  a38=(a38-a41);
  a03=(a03+a38);
  a38=(a24*a48);
  a03=(a03+a38);
  a38=(a44*a04);
  a38=(a38-a01);
  a38=(a02*a38);
  a38=(a38+a48);
  a03=(a03+a38);
  a03=(-a03);
  if (res[1]!=0) res[1][13]=a03;
  if (res[1]!=0) res[1][14]=a37;
  a03=(a29*a44);
  a03=(a24*a03);
  a03=(-a03);
  if (res[1]!=0) res[1][15]=a03;
  a03=(a00*a44);
  a03=(a03-a35);
  a03=(a22*a03);
  a47=(a47*a26);
  a03=(a03+a47);
  a47=(a44*a06);
  a47=(a13+a47);
  a47=(a24*a47);
  a03=(a03+a47);
  a15=(a02*a15);
  a03=(a03+a15);
  a03=(-a03);
  if (res[1]!=0) res[1][16]=a03;
  a03=(a44*a00);
  a03=(a03-a35);
  a03=(a14*a03);
  a46=(a46*a06);
  a46=(a46+a19);
  a46=(a22*a46);
  a03=(a03-a46);
  a46=(a44*a25);
  a46=(a46-a27);
  a46=(a24*a46);
  a03=(a03+a46);
  a44=(a44*a17);
  a44=(a44+a12);
  a44=(a02*a44);
  a03=(a03-a44);
  a03=(-a03);
  if (res[1]!=0) res[1][17]=a03;
  a40=(-a40);
  if (res[1]!=0) res[1][18]=a40;
  a40=(a49*a33);
  a40=(a40-a50);
  a03=(a14*a40);
  a44=(a52*a05);
  a46=(a51*a36);
  a46=(a46+a08);
  a46=(a22*a46);
  a44=(a44-a46);
  a03=(a03+a44);
  a44=(a24*a53);
  a03=(a03+a44);
  a44=(a49*a04);
  a44=(a44-a01);
  a44=(a02*a44);
  a44=(a44+a53);
  a03=(a03+a44);
  a03=(-a03);
  if (res[1]!=0) res[1][19]=a03;
  if (res[1]!=0) res[1][20]=a37;
  a03=(a29*a49);
  a03=(a24*a03);
  a03=(-a03);
  if (res[1]!=0) res[1][21]=a03;
  a03=(a00*a49);
  a03=(a03-a35);
  a03=(a22*a03);
  a52=(a52*a26);
  a03=(a03+a52);
  a52=(a49*a06);
  a52=(a13+a52);
  a52=(a24*a52);
  a03=(a03+a52);
  a40=(a02*a40);
  a03=(a03+a40);
  a03=(-a03);
  if (res[1]!=0) res[1][22]=a03;
  a03=(a49*a00);
  a03=(a03-a35);
  a03=(a14*a03);
  a51=(a51*a06);
  a51=(a51+a19);
  a51=(a22*a51);
  a03=(a03-a51);
  a51=(a49*a25);
  a51=(a51-a27);
  a51=(a24*a51);
  a03=(a03+a51);
  a49=(a49*a17);
  a49=(a49+a12);
  a49=(a02*a49);
  a03=(a03-a49);
  a03=(-a03);
  if (res[1]!=0) res[1][23]=a03;
  a45=(-a45);
  if (res[1]!=0) res[1][24]=a45;
  a45=(a54*a33);
  a45=(a45-a50);
  a03=(a14*a45);
  a49=(a57*a05);
  a51=(a56*a36);
  a51=(a51+a08);
  a51=(a22*a51);
  a49=(a49-a51);
  a03=(a03+a49);
  a49=(a24*a58);
  a03=(a03+a49);
  a49=(a54*a04);
  a49=(a49-a01);
  a49=(a02*a49);
  a49=(a49+a58);
  a03=(a03+a49);
  a03=(-a03);
  if (res[1]!=0) res[1][25]=a03;
  if (res[1]!=0) res[1][26]=a37;
  a03=(a29*a54);
  a03=(a24*a03);
  a03=(-a03);
  if (res[1]!=0) res[1][27]=a03;
  a03=(a00*a54);
  a03=(a03-a35);
  a03=(a22*a03);
  a57=(a57*a26);
  a03=(a03+a57);
  a57=(a54*a06);
  a57=(a13+a57);
  a57=(a24*a57);
  a03=(a03+a57);
  a45=(a02*a45);
  a03=(a03+a45);
  a03=(-a03);
  if (res[1]!=0) res[1][28]=a03;
  a03=(a54*a00);
  a03=(a03-a35);
  a03=(a14*a03);
  a56=(a56*a06);
  a56=(a56+a19);
  a56=(a22*a56);
  a03=(a03-a56);
  a56=(a54*a25);
  a56=(a56-a27);
  a56=(a24*a56);
  a03=(a03+a56);
  a54=(a54*a17);
  a54=(a54+a12);
  a54=(a02*a54);
  a03=(a03-a54);
  a03=(-a03);
  if (res[1]!=0) res[1][29]=a03;
  a59=(-a59);
  if (res[1]!=0) res[1][30]=a59;
  a33=(a55*a33);
  a33=(a33-a50);
  a50=(a14*a33);
  a05=(a61*a05);
  a36=(a60*a36);
  a36=(a36+a08);
  a36=(a22*a36);
  a05=(a05-a36);
  a50=(a50+a05);
  a05=(a24*a34);
  a50=(a50+a05);
  a04=(a55*a04);
  a04=(a04-a01);
  a04=(a02*a04);
  a04=(a04+a34);
  a50=(a50+a04);
  a50=(-a50);
  if (res[1]!=0) res[1][31]=a50;
  if (res[1]!=0) res[1][32]=a37;
  a29=(a29*a55);
  a29=(a24*a29);
  a29=(-a29);
  if (res[1]!=0) res[1][33]=a29;
  a29=(a00*a55);
  a29=(a29-a35);
  a29=(a22*a29);
  a61=(a61*a26);
  a29=(a29+a61);
  a61=(a55*a06);
  a13=(a13+a61);
  a13=(a24*a13);
  a29=(a29+a13);
  a33=(a02*a33);
  a29=(a29+a33);
  a29=(-a29);
  if (res[1]!=0) res[1][34]=a29;
  a00=(a55*a00);
  a00=(a00-a35);
  a14=(a14*a00);
  a60=(a60*a06);
  a60=(a60+a19);
  a22=(a22*a60);
  a14=(a14-a22);
  a25=(a55*a25);
  a25=(a25-a27);
  a24=(a24*a25);
  a14=(a14+a24);
  a55=(a55*a17);
  a55=(a55+a12);
  a02=(a02*a55);
  a14=(a14-a02);
  a14=(-a14);
  if (res[1]!=0) res[1][35]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
