/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {16, 1, 1};
static const casadi_int casadi_s4[3] = {6, 1, 1};
static const casadi_int casadi_s5[3] = {6, 6, 1};
static const casadi_int casadi_s6[3] = {6, 0, 1};

/* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt:(i0[4],i1[2],i2[0],i3[16])->(o0[6],o1[6x6],o2[6x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70;
  a00=arg[0]? arg[0][2] : 0;
  a01=arg[0]? arg[0][3] : 0;
  a02=5.0000000000000000e-01;
  a03=arg[1]? arg[1][1] : 0;
  a04=tan(a03);
  a05=(a02*a04);
  a06=atan(a05);
  a01=(a01+a06);
  a07=cos(a01);
  a08=(a00*a07);
  a09=(a08+a08);
  a10=(a09*a08);
  a01=sin(a01);
  a11=(a00*a01);
  a12=(a11+a11);
  a13=(a12*a11);
  a10=(a10+a13);
  a13=arg[0]? arg[0][1] : 0;
  a14=arg[3]? arg[3][5] : 0;
  a14=(a13-a14);
  a15=(a14+a14);
  a16=(a01*a15);
  a17=arg[0]? arg[0][0] : 0;
  a18=arg[3]? arg[3][4] : 0;
  a18=(a17-a18);
  a19=(a18+a18);
  a20=(a07*a19);
  a16=(a16+a20);
  a20=arg[1]? arg[1][0] : 0;
  a21=(a16*a20);
  a21=(a10+a21);
  a22=(a00*a15);
  a23=(a07*a22);
  a24=(a00*a19);
  a25=(a01*a24);
  a23=(a23-a25);
  a25=sin(a06);
  a26=(a00*a25);
  a27=2.5000000000000000e+00;
  a26=(a26/a27);
  a27=(a23*a26);
  a21=(a21+a27);
  a27=2.3999999999999999e+00;
  a28=(a19*a08);
  a29=(a15*a11);
  a28=(a28+a29);
  a18=casadi_sq(a18);
  a14=casadi_sq(a14);
  a18=(a18+a14);
  a14=64.;
  a18=(a18-a14);
  a28=(a28+a18);
  a28=(a27*a28);
  a21=(a21+a28);
  a28=cos(a03);
  a18=casadi_sq(a28);
  a02=(a02/a18);
  a29=1.;
  a05=casadi_sq(a05);
  a29=(a29+a05);
  a05=(a02/a29);
  a30=(a07*a05);
  a31=(a00*a30);
  a32=(a15*a31);
  a33=(a01*a05);
  a34=(a00*a33);
  a35=(a19*a34);
  a32=(a32-a35);
  a35=(a32*a03);
  a21=(a21+a35);
  if (res[0]!=0) res[0][0]=a21;
  a21=arg[3]? arg[3][7] : 0;
  a21=(a13-a21);
  a35=(a21+a21);
  a36=(a01*a35);
  a37=arg[3]? arg[3][6] : 0;
  a37=(a17-a37);
  a38=(a37+a37);
  a39=(a07*a38);
  a36=(a36+a39);
  a39=(a36*a20);
  a39=(a10+a39);
  a40=(a00*a35);
  a41=(a07*a40);
  a42=(a00*a38);
  a43=(a01*a42);
  a41=(a41-a43);
  a43=(a41*a26);
  a39=(a39+a43);
  a43=(a38*a08);
  a44=(a35*a11);
  a43=(a43+a44);
  a37=casadi_sq(a37);
  a21=casadi_sq(a21);
  a37=(a37+a21);
  a37=(a37-a14);
  a43=(a43+a37);
  a43=(a27*a43);
  a39=(a39+a43);
  a43=(a35*a31);
  a37=(a38*a34);
  a43=(a43-a37);
  a37=(a43*a03);
  a39=(a39+a37);
  if (res[0]!=0) res[0][1]=a39;
  a39=arg[3]? arg[3][9] : 0;
  a39=(a13-a39);
  a37=(a39+a39);
  a21=(a01*a37);
  a44=arg[3]? arg[3][8] : 0;
  a44=(a17-a44);
  a45=(a44+a44);
  a46=(a07*a45);
  a21=(a21+a46);
  a46=(a21*a20);
  a46=(a10+a46);
  a47=(a00*a37);
  a48=(a07*a47);
  a49=(a00*a45);
  a50=(a01*a49);
  a48=(a48-a50);
  a50=(a48*a26);
  a46=(a46+a50);
  a50=(a45*a08);
  a51=(a37*a11);
  a50=(a50+a51);
  a44=casadi_sq(a44);
  a39=casadi_sq(a39);
  a44=(a44+a39);
  a44=(a44-a14);
  a50=(a50+a44);
  a50=(a27*a50);
  a46=(a46+a50);
  a50=(a37*a31);
  a44=(a45*a34);
  a50=(a50-a44);
  a44=(a50*a03);
  a46=(a46+a44);
  if (res[0]!=0) res[0][2]=a46;
  a46=arg[3]? arg[3][11] : 0;
  a46=(a13-a46);
  a44=(a46+a46);
  a14=(a01*a44);
  a39=arg[3]? arg[3][10] : 0;
  a39=(a17-a39);
  a51=(a39+a39);
  a52=(a07*a51);
  a14=(a14+a52);
  a52=(a14*a20);
  a52=(a10+a52);
  a53=(a00*a44);
  a54=(a07*a53);
  a55=(a00*a51);
  a56=(a01*a55);
  a54=(a54-a56);
  a56=(a54*a26);
  a52=(a52+a56);
  a56=(a51*a08);
  a57=(a44*a11);
  a56=(a56+a57);
  a39=casadi_sq(a39);
  a46=casadi_sq(a46);
  a39=(a39+a46);
  a46=4.4100000000000001e+00;
  a39=(a39-a46);
  a56=(a56+a39);
  a56=(a27*a56);
  a52=(a52+a56);
  a56=(a44*a31);
  a39=(a51*a34);
  a56=(a56-a39);
  a39=(a56*a03);
  a52=(a52+a39);
  if (res[0]!=0) res[0][3]=a52;
  a52=arg[3]? arg[3][13] : 0;
  a52=(a13-a52);
  a39=(a52+a52);
  a57=(a01*a39);
  a58=arg[3]? arg[3][12] : 0;
  a58=(a17-a58);
  a59=(a58+a58);
  a60=(a07*a59);
  a57=(a57+a60);
  a60=(a57*a20);
  a60=(a10+a60);
  a61=(a00*a39);
  a62=(a07*a61);
  a63=(a00*a59);
  a64=(a01*a63);
  a62=(a62-a64);
  a64=(a62*a26);
  a60=(a60+a64);
  a64=(a59*a08);
  a65=(a39*a11);
  a64=(a64+a65);
  a58=casadi_sq(a58);
  a52=casadi_sq(a52);
  a58=(a58+a52);
  a58=(a58-a46);
  a64=(a64+a58);
  a64=(a27*a64);
  a60=(a60+a64);
  a64=(a39*a31);
  a58=(a59*a34);
  a64=(a64-a58);
  a58=(a64*a03);
  a60=(a60+a58);
  if (res[0]!=0) res[0][4]=a60;
  a60=arg[3]? arg[3][15] : 0;
  a13=(a13-a60);
  a60=(a13+a13);
  a58=(a01*a60);
  a52=arg[3]? arg[3][14] : 0;
  a17=(a17-a52);
  a52=(a17+a17);
  a65=(a07*a52);
  a58=(a58+a65);
  a65=(a58*a20);
  a10=(a10+a65);
  a65=(a00*a60);
  a66=(a07*a65);
  a67=(a00*a52);
  a68=(a01*a67);
  a66=(a66-a68);
  a68=(a66*a26);
  a10=(a10+a68);
  a68=(a52*a08);
  a69=(a60*a11);
  a68=(a68+a69);
  a17=casadi_sq(a17);
  a13=casadi_sq(a13);
  a17=(a17+a13);
  a17=(a17-a46);
  a68=(a68+a17);
  a68=(a27*a68);
  a10=(a10+a68);
  a68=(a60*a31);
  a17=(a52*a34);
  a68=(a68-a17);
  a17=(a68*a03);
  a10=(a10+a17);
  if (res[0]!=0) res[0][5]=a10;
  if (res[1]!=0) res[1][0]=a16;
  a16=(a31+a31);
  a16=(a11*a16);
  a10=(a12*a31);
  a16=(a16+a10);
  a10=(a34+a34);
  a10=(a08*a10);
  a17=(a09*a34);
  a10=(a10+a17);
  a16=(a16-a10);
  a10=(a15*a30);
  a17=(a19*a33);
  a10=(a10-a17);
  a17=(a20*a10);
  a17=(a16+a17);
  a46=4.0000000000000002e-01;
  a06=cos(a06);
  a06=(a06*a05);
  a06=(a00*a06);
  a06=(a46*a06);
  a13=(a23*a06);
  a69=(a22*a33);
  a70=(a24*a30);
  a69=(a69+a70);
  a69=(a26*a69);
  a13=(a13-a69);
  a17=(a17+a13);
  a13=(a27*a32);
  a17=(a17+a13);
  a18=(a02/a18);
  a28=(a28+a28);
  a13=sin(a03);
  a28=(a28*a13);
  a18=(a18*a28);
  a18=(a18/a29);
  a29=(a05/a29);
  a04=(a04*a02);
  a29=(a29*a04);
  a18=(a18-a29);
  a29=(a07*a18);
  a04=(a05*a33);
  a29=(a29-a04);
  a29=(a00*a29);
  a04=(a15*a29);
  a02=(a05*a30);
  a18=(a01*a18);
  a02=(a02+a18);
  a02=(a00*a02);
  a18=(a19*a02);
  a04=(a04-a18);
  a04=(a03*a04);
  a04=(a04+a32);
  a17=(a17+a04);
  if (res[1]!=0) res[1][1]=a17;
  a17=2.;
  a04=(a17*a07);
  a04=(a20*a04);
  a32=(a17*a00);
  a18=(a01*a32);
  a18=(a26*a18);
  a04=(a04-a18);
  a18=(a17*a08);
  a28=(a18+a19);
  a28=(a27*a28);
  a28=(a04+a28);
  a34=(a17*a34);
  a34=(a03*a34);
  a28=(a28-a34);
  if (res[1]!=0) res[1][2]=a28;
  a28=(a17*a01);
  a28=(a20*a28);
  a32=(a07*a32);
  a32=(a26*a32);
  a28=(a28+a32);
  a32=(a17*a11);
  a13=(a32+a15);
  a13=(a27*a13);
  a13=(a28+a13);
  a17=(a17*a31);
  a17=(a03*a17);
  a13=(a13+a17);
  if (res[1]!=0) res[1][3]=a13;
  a13=(a07+a07);
  a13=(a08*a13);
  a31=(a09*a07);
  a13=(a13+a31);
  a31=(a01+a01);
  a31=(a11*a31);
  a69=(a12*a01);
  a31=(a31+a69);
  a13=(a13+a31);
  a31=(a07*a15);
  a69=(a01*a19);
  a31=(a31-a69);
  a31=(a26*a31);
  a46=(a46*a25);
  a23=(a23*a46);
  a31=(a31+a23);
  a31=(a13+a31);
  a23=(a19*a07);
  a25=(a15*a01);
  a23=(a23+a25);
  a23=(a27*a23);
  a31=(a31+a23);
  a10=(a03*a10);
  a31=(a31+a10);
  if (res[1]!=0) res[1][4]=a31;
  a31=(a11*a09);
  a10=(a12*a08);
  a31=(a31+a10);
  a12=(a08*a12);
  a09=(a09*a11);
  a12=(a12+a09);
  a31=(a31-a12);
  a12=(a15*a07);
  a09=(a19*a01);
  a12=(a12-a09);
  a12=(a20*a12);
  a12=(a31+a12);
  a22=(a22*a01);
  a24=(a24*a07);
  a22=(a22+a24);
  a22=(a26*a22);
  a12=(a12-a22);
  a22=(a15*a08);
  a24=(a19*a11);
  a22=(a22-a24);
  a22=(a27*a22);
  a12=(a12+a22);
  a22=(a05*a01);
  a22=(a00*a22);
  a15=(a15*a22);
  a05=(a05*a07);
  a00=(a00*a05);
  a19=(a19*a00);
  a15=(a15+a19);
  a15=(a03*a15);
  a12=(a12-a15);
  if (res[1]!=0) res[1][5]=a12;
  if (res[1]!=0) res[1][6]=a36;
  a36=(a35*a30);
  a12=(a38*a33);
  a36=(a36-a12);
  a12=(a20*a36);
  a12=(a16+a12);
  a15=(a41*a06);
  a19=(a40*a33);
  a05=(a42*a30);
  a19=(a19+a05);
  a19=(a26*a19);
  a15=(a15-a19);
  a12=(a12+a15);
  a15=(a27*a43);
  a12=(a12+a15);
  a15=(a35*a29);
  a19=(a38*a02);
  a15=(a15-a19);
  a15=(a03*a15);
  a15=(a15+a43);
  a12=(a12+a15);
  if (res[1]!=0) res[1][7]=a12;
  a12=(a18+a38);
  a12=(a27*a12);
  a12=(a04+a12);
  a12=(a12-a34);
  if (res[1]!=0) res[1][8]=a12;
  a12=(a32+a35);
  a12=(a27*a12);
  a12=(a28+a12);
  a12=(a12+a17);
  if (res[1]!=0) res[1][9]=a12;
  a12=(a07*a35);
  a15=(a01*a38);
  a12=(a12-a15);
  a12=(a26*a12);
  a41=(a41*a46);
  a12=(a12+a41);
  a12=(a13+a12);
  a41=(a38*a07);
  a15=(a35*a01);
  a41=(a41+a15);
  a41=(a27*a41);
  a12=(a12+a41);
  a36=(a03*a36);
  a12=(a12+a36);
  if (res[1]!=0) res[1][10]=a12;
  a12=(a35*a07);
  a36=(a38*a01);
  a12=(a12-a36);
  a12=(a20*a12);
  a12=(a31+a12);
  a40=(a40*a01);
  a42=(a42*a07);
  a40=(a40+a42);
  a40=(a26*a40);
  a12=(a12-a40);
  a40=(a35*a08);
  a42=(a38*a11);
  a40=(a40-a42);
  a40=(a27*a40);
  a12=(a12+a40);
  a35=(a35*a22);
  a38=(a38*a00);
  a35=(a35+a38);
  a35=(a03*a35);
  a12=(a12-a35);
  if (res[1]!=0) res[1][11]=a12;
  if (res[1]!=0) res[1][12]=a21;
  a21=(a37*a30);
  a12=(a45*a33);
  a21=(a21-a12);
  a12=(a20*a21);
  a12=(a16+a12);
  a35=(a48*a06);
  a38=(a47*a33);
  a40=(a49*a30);
  a38=(a38+a40);
  a38=(a26*a38);
  a35=(a35-a38);
  a12=(a12+a35);
  a35=(a27*a50);
  a12=(a12+a35);
  a35=(a37*a29);
  a38=(a45*a02);
  a35=(a35-a38);
  a35=(a03*a35);
  a35=(a35+a50);
  a12=(a12+a35);
  if (res[1]!=0) res[1][13]=a12;
  a12=(a18+a45);
  a12=(a27*a12);
  a12=(a04+a12);
  a12=(a12-a34);
  if (res[1]!=0) res[1][14]=a12;
  a12=(a32+a37);
  a12=(a27*a12);
  a12=(a28+a12);
  a12=(a12+a17);
  if (res[1]!=0) res[1][15]=a12;
  a12=(a07*a37);
  a35=(a01*a45);
  a12=(a12-a35);
  a12=(a26*a12);
  a48=(a48*a46);
  a12=(a12+a48);
  a12=(a13+a12);
  a48=(a45*a07);
  a35=(a37*a01);
  a48=(a48+a35);
  a48=(a27*a48);
  a12=(a12+a48);
  a21=(a03*a21);
  a12=(a12+a21);
  if (res[1]!=0) res[1][16]=a12;
  a12=(a37*a07);
  a21=(a45*a01);
  a12=(a12-a21);
  a12=(a20*a12);
  a12=(a31+a12);
  a47=(a47*a01);
  a49=(a49*a07);
  a47=(a47+a49);
  a47=(a26*a47);
  a12=(a12-a47);
  a47=(a37*a08);
  a49=(a45*a11);
  a47=(a47-a49);
  a47=(a27*a47);
  a12=(a12+a47);
  a37=(a37*a22);
  a45=(a45*a00);
  a37=(a37+a45);
  a37=(a03*a37);
  a12=(a12-a37);
  if (res[1]!=0) res[1][17]=a12;
  if (res[1]!=0) res[1][18]=a14;
  a14=(a44*a30);
  a12=(a51*a33);
  a14=(a14-a12);
  a12=(a20*a14);
  a12=(a16+a12);
  a37=(a54*a06);
  a45=(a53*a33);
  a47=(a55*a30);
  a45=(a45+a47);
  a45=(a26*a45);
  a37=(a37-a45);
  a12=(a12+a37);
  a37=(a27*a56);
  a12=(a12+a37);
  a37=(a44*a29);
  a45=(a51*a02);
  a37=(a37-a45);
  a37=(a03*a37);
  a37=(a37+a56);
  a12=(a12+a37);
  if (res[1]!=0) res[1][19]=a12;
  a12=(a18+a51);
  a12=(a27*a12);
  a12=(a04+a12);
  a12=(a12-a34);
  if (res[1]!=0) res[1][20]=a12;
  a12=(a32+a44);
  a12=(a27*a12);
  a12=(a28+a12);
  a12=(a12+a17);
  if (res[1]!=0) res[1][21]=a12;
  a12=(a07*a44);
  a37=(a01*a51);
  a12=(a12-a37);
  a12=(a26*a12);
  a54=(a54*a46);
  a12=(a12+a54);
  a12=(a13+a12);
  a54=(a51*a07);
  a37=(a44*a01);
  a54=(a54+a37);
  a54=(a27*a54);
  a12=(a12+a54);
  a14=(a03*a14);
  a12=(a12+a14);
  if (res[1]!=0) res[1][22]=a12;
  a12=(a44*a07);
  a14=(a51*a01);
  a12=(a12-a14);
  a12=(a20*a12);
  a12=(a31+a12);
  a53=(a53*a01);
  a55=(a55*a07);
  a53=(a53+a55);
  a53=(a26*a53);
  a12=(a12-a53);
  a53=(a44*a08);
  a55=(a51*a11);
  a53=(a53-a55);
  a53=(a27*a53);
  a12=(a12+a53);
  a44=(a44*a22);
  a51=(a51*a00);
  a44=(a44+a51);
  a44=(a03*a44);
  a12=(a12-a44);
  if (res[1]!=0) res[1][23]=a12;
  if (res[1]!=0) res[1][24]=a57;
  a57=(a39*a30);
  a12=(a59*a33);
  a57=(a57-a12);
  a12=(a20*a57);
  a12=(a16+a12);
  a44=(a62*a06);
  a51=(a61*a33);
  a53=(a63*a30);
  a51=(a51+a53);
  a51=(a26*a51);
  a44=(a44-a51);
  a12=(a12+a44);
  a44=(a27*a64);
  a12=(a12+a44);
  a44=(a39*a29);
  a51=(a59*a02);
  a44=(a44-a51);
  a44=(a03*a44);
  a44=(a44+a64);
  a12=(a12+a44);
  if (res[1]!=0) res[1][25]=a12;
  a12=(a18+a59);
  a12=(a27*a12);
  a12=(a04+a12);
  a12=(a12-a34);
  if (res[1]!=0) res[1][26]=a12;
  a12=(a32+a39);
  a12=(a27*a12);
  a12=(a28+a12);
  a12=(a12+a17);
  if (res[1]!=0) res[1][27]=a12;
  a12=(a07*a39);
  a44=(a01*a59);
  a12=(a12-a44);
  a12=(a26*a12);
  a62=(a62*a46);
  a12=(a12+a62);
  a12=(a13+a12);
  a62=(a59*a07);
  a44=(a39*a01);
  a62=(a62+a44);
  a62=(a27*a62);
  a12=(a12+a62);
  a57=(a03*a57);
  a12=(a12+a57);
  if (res[1]!=0) res[1][28]=a12;
  a12=(a39*a07);
  a57=(a59*a01);
  a12=(a12-a57);
  a12=(a20*a12);
  a12=(a31+a12);
  a61=(a61*a01);
  a63=(a63*a07);
  a61=(a61+a63);
  a61=(a26*a61);
  a12=(a12-a61);
  a61=(a39*a08);
  a63=(a59*a11);
  a61=(a61-a63);
  a61=(a27*a61);
  a12=(a12+a61);
  a39=(a39*a22);
  a59=(a59*a00);
  a39=(a39+a59);
  a39=(a03*a39);
  a12=(a12-a39);
  if (res[1]!=0) res[1][29]=a12;
  if (res[1]!=0) res[1][30]=a58;
  a58=(a60*a30);
  a12=(a52*a33);
  a58=(a58-a12);
  a12=(a20*a58);
  a16=(a16+a12);
  a06=(a66*a06);
  a33=(a65*a33);
  a30=(a67*a30);
  a33=(a33+a30);
  a33=(a26*a33);
  a06=(a06-a33);
  a16=(a16+a06);
  a06=(a27*a68);
  a16=(a16+a06);
  a29=(a60*a29);
  a02=(a52*a02);
  a29=(a29-a02);
  a29=(a03*a29);
  a29=(a29+a68);
  a16=(a16+a29);
  if (res[1]!=0) res[1][31]=a16;
  a18=(a18+a52);
  a18=(a27*a18);
  a04=(a04+a18);
  a04=(a04-a34);
  if (res[1]!=0) res[1][32]=a04;
  a32=(a32+a60);
  a32=(a27*a32);
  a28=(a28+a32);
  a28=(a28+a17);
  if (res[1]!=0) res[1][33]=a28;
  a28=(a07*a60);
  a17=(a01*a52);
  a28=(a28-a17);
  a28=(a26*a28);
  a66=(a66*a46);
  a28=(a28+a66);
  a13=(a13+a28);
  a28=(a52*a07);
  a66=(a60*a01);
  a28=(a28+a66);
  a28=(a27*a28);
  a13=(a13+a28);
  a58=(a03*a58);
  a13=(a13+a58);
  if (res[1]!=0) res[1][34]=a13;
  a13=(a60*a07);
  a58=(a52*a01);
  a13=(a13-a58);
  a20=(a20*a13);
  a31=(a31+a20);
  a65=(a65*a01);
  a67=(a67*a07);
  a65=(a65+a67);
  a26=(a26*a65);
  a31=(a31-a26);
  a08=(a60*a08);
  a11=(a52*a11);
  a08=(a08-a11);
  a27=(a27*a08);
  a31=(a31+a27);
  a60=(a60*a22);
  a52=(a52*a00);
  a60=(a60+a52);
  a03=(a03*a60);
  a31=(a31-a03);
  if (res[1]!=0) res[1][35]=a31;
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
