/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) KinematicTrackingMPC_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {22, 1, 1};
static const casadi_int casadi_s4[3] = {6, 1, 1};

/* KinematicTrackingMPC_constr_h_fun:(i0[4],i1[2],i2[0],i3[22])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24;
  a00=arg[0]? arg[0][3] : 0;
  a01=5.0000000000000000e-01;
  a02=arg[1]? arg[1][1] : 0;
  a03=tan(a02);
  a03=(a01*a03);
  a04=atan(a03);
  a00=(a00+a04);
  a05=sin(a00);
  a06=arg[3]? arg[3][6] : 0;
  a07=arg[0]? arg[0][1] : 0;
  a08=arg[3]? arg[3][5] : 0;
  a08=(a07-a08);
  a09=casadi_sign(a08);
  a09=(a06*a09);
  a10=(a05*a09);
  a00=cos(a00);
  a11=1.;
  a12=(a11-a06);
  a13=(a00*a12);
  a10=(a10+a13);
  a13=arg[1]? arg[1][0] : 0;
  a10=(a10*a13);
  a14=arg[0]? arg[0][2] : 0;
  a15=(a14*a09);
  a15=(a00*a15);
  a16=(a14*a12);
  a16=(a05*a16);
  a15=(a15-a16);
  a04=sin(a04);
  a04=(a14*a04);
  a16=2.5000000000000000e+00;
  a04=(a04/a16);
  a15=(a15*a04);
  a10=(a10+a15);
  a15=2.3999999999999999e+00;
  a17=(a14*a00);
  a18=(a12*a17);
  a19=(a14*a05);
  a20=(a09*a19);
  a18=(a18+a20);
  a20=2.2000000000000002e+00;
  a21=arg[0]? arg[0][0] : 0;
  a22=arg[3]? arg[3][4] : 0;
  a22=(a21-a22);
  a23=3.;
  a22=(a22-a23);
  a22=(a22-a16);
  a22=(a12*a22);
  a08=casadi_fabs(a08);
  a24=2.0000000000000001e-01;
  a08=(a08-a24);
  a08=(a08-a11);
  a06=(a06*a08);
  a22=(a22+a06);
  a22=(a20*a22);
  a18=(a18+a22);
  a18=(a15*a18);
  a10=(a10+a18);
  a18=cos(a02);
  a18=casadi_sq(a18);
  a01=(a01/a18);
  a03=casadi_sq(a03);
  a03=(a11+a03);
  a01=(a01/a03);
  a03=(a00*a01);
  a03=(a14*a03);
  a09=(a09*a03);
  a01=(a05*a01);
  a01=(a14*a01);
  a12=(a12*a01);
  a09=(a09-a12);
  a09=(a09*a02);
  a10=(a10+a09);
  if (res[0]!=0) res[0][0]=a10;
  a10=arg[3]? arg[3][9] : 0;
  a09=arg[3]? arg[3][8] : 0;
  a09=(a07-a09);
  a12=casadi_sign(a09);
  a12=(a10*a12);
  a18=(a05*a12);
  a22=(a11-a10);
  a06=(a00*a22);
  a18=(a18+a06);
  a18=(a18*a13);
  a06=(a14*a12);
  a06=(a00*a06);
  a08=(a14*a22);
  a08=(a05*a08);
  a06=(a06-a08);
  a06=(a06*a04);
  a18=(a18+a06);
  a06=(a22*a17);
  a08=(a12*a19);
  a06=(a06+a08);
  a08=arg[3]? arg[3][7] : 0;
  a08=(a21-a08);
  a08=(a08-a23);
  a08=(a08-a16);
  a08=(a22*a08);
  a09=casadi_fabs(a09);
  a09=(a09-a24);
  a09=(a09-a11);
  a10=(a10*a09);
  a08=(a08+a10);
  a08=(a20*a08);
  a06=(a06+a08);
  a06=(a15*a06);
  a18=(a18+a06);
  a12=(a12*a03);
  a22=(a22*a01);
  a12=(a12-a22);
  a12=(a12*a02);
  a18=(a18+a12);
  if (res[0]!=0) res[0][1]=a18;
  a18=arg[3]? arg[3][12] : 0;
  a12=arg[3]? arg[3][11] : 0;
  a12=(a07-a12);
  a22=casadi_sign(a12);
  a22=(a18*a22);
  a06=(a05*a22);
  a08=(a11-a18);
  a10=(a00*a08);
  a06=(a06+a10);
  a06=(a06*a13);
  a10=(a14*a22);
  a10=(a00*a10);
  a09=(a14*a08);
  a09=(a05*a09);
  a10=(a10-a09);
  a10=(a10*a04);
  a06=(a06+a10);
  a10=(a08*a17);
  a09=(a22*a19);
  a10=(a10+a09);
  a09=arg[3]? arg[3][10] : 0;
  a09=(a21-a09);
  a09=(a09-a23);
  a09=(a09-a16);
  a09=(a08*a09);
  a12=casadi_fabs(a12);
  a12=(a12-a24);
  a12=(a12-a11);
  a18=(a18*a12);
  a09=(a09+a18);
  a09=(a20*a09);
  a10=(a10+a09);
  a10=(a15*a10);
  a06=(a06+a10);
  a22=(a22*a03);
  a08=(a08*a01);
  a22=(a22-a08);
  a22=(a22*a02);
  a06=(a06+a22);
  if (res[0]!=0) res[0][2]=a06;
  a06=arg[3]? arg[3][15] : 0;
  a22=arg[3]? arg[3][14] : 0;
  a22=(a07-a22);
  a08=casadi_sign(a22);
  a08=(a06*a08);
  a10=(a05*a08);
  a09=(a11-a06);
  a18=(a00*a09);
  a10=(a10+a18);
  a10=(a10*a13);
  a18=(a14*a08);
  a18=(a00*a18);
  a12=(a14*a09);
  a12=(a05*a12);
  a18=(a18-a12);
  a18=(a18*a04);
  a10=(a10+a18);
  a18=(a09*a17);
  a12=(a08*a19);
  a18=(a18+a12);
  a12=arg[3]? arg[3][13] : 0;
  a12=(a21-a12);
  a12=(a12-a23);
  a12=(a12-a16);
  a12=(a09*a12);
  a22=casadi_fabs(a22);
  a22=(a22-a24);
  a22=(a22-a11);
  a06=(a06*a22);
  a12=(a12+a06);
  a12=(a20*a12);
  a18=(a18+a12);
  a18=(a15*a18);
  a10=(a10+a18);
  a08=(a08*a03);
  a09=(a09*a01);
  a08=(a08-a09);
  a08=(a08*a02);
  a10=(a10+a08);
  if (res[0]!=0) res[0][3]=a10;
  a10=arg[3]? arg[3][18] : 0;
  a08=arg[3]? arg[3][17] : 0;
  a08=(a07-a08);
  a09=casadi_sign(a08);
  a09=(a10*a09);
  a18=(a05*a09);
  a12=(a11-a10);
  a06=(a00*a12);
  a18=(a18+a06);
  a18=(a18*a13);
  a06=(a14*a09);
  a06=(a00*a06);
  a22=(a14*a12);
  a22=(a05*a22);
  a06=(a06-a22);
  a06=(a06*a04);
  a18=(a18+a06);
  a06=(a12*a17);
  a22=(a09*a19);
  a06=(a06+a22);
  a22=arg[3]? arg[3][16] : 0;
  a22=(a21-a22);
  a22=(a22-a23);
  a22=(a22-a16);
  a22=(a12*a22);
  a08=casadi_fabs(a08);
  a08=(a08-a24);
  a08=(a08-a11);
  a10=(a10*a08);
  a22=(a22+a10);
  a22=(a20*a22);
  a06=(a06+a22);
  a06=(a15*a06);
  a18=(a18+a06);
  a09=(a09*a03);
  a12=(a12*a01);
  a09=(a09-a12);
  a09=(a09*a02);
  a18=(a18+a09);
  if (res[0]!=0) res[0][4]=a18;
  a18=arg[3]? arg[3][21] : 0;
  a09=arg[3]? arg[3][20] : 0;
  a07=(a07-a09);
  a09=casadi_sign(a07);
  a09=(a18*a09);
  a12=(a05*a09);
  a06=(a11-a18);
  a22=(a00*a06);
  a12=(a12+a22);
  a12=(a12*a13);
  a13=(a14*a09);
  a00=(a00*a13);
  a14=(a14*a06);
  a05=(a05*a14);
  a00=(a00-a05);
  a00=(a00*a04);
  a12=(a12+a00);
  a17=(a06*a17);
  a19=(a09*a19);
  a17=(a17+a19);
  a19=arg[3]? arg[3][19] : 0;
  a21=(a21-a19);
  a21=(a21-a23);
  a21=(a21-a16);
  a21=(a06*a21);
  a07=casadi_fabs(a07);
  a07=(a07-a24);
  a07=(a07-a11);
  a18=(a18*a07);
  a21=(a21+a18);
  a20=(a20*a21);
  a17=(a17+a20);
  a15=(a15*a17);
  a12=(a12+a15);
  a09=(a09*a03);
  a06=(a06*a01);
  a09=(a09-a06);
  a09=(a09*a02);
  a12=(a12+a09);
  if (res[0]!=0) res[0][5]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void KinematicTrackingMPC_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int KinematicTrackingMPC_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int KinematicTrackingMPC_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real KinematicTrackingMPC_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* KinematicTrackingMPC_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* KinematicTrackingMPC_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* KinematicTrackingMPC_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* KinematicTrackingMPC_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int KinematicTrackingMPC_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
